<?php


namespace app\home\controller;

use app\home\ApiBaseController;//不需要验证
use app\home\UserBaseController;

//需要验证

class Base extends UserBaseController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}