<?php


namespace app\home;


use app\BaseController;
use app\common\model\UserModel;

class ApiBaseController extends BaseController
{
    public function initialize()
    {
        $user_info = (new UserModel())->find(1);
        session('home_user',$user_info);
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}