<?php


namespace app\admin\controller;


use app\common\model\SysConfig as models;
use app\common\traites\PublicCrudTrait;
use think\exception\ValidateException;
use \app\validate\SysConfig as validates;

class SysConfig extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     *配置控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件

        //->page($page, $limit)
        $list = $this->model->order('id desc')->select()->toArray();
        return $this->success($list);
    }

    /**
     * 添加
     */
    public function add()
    {
        //过滤数据
        $postField = 'name,value,mark';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        $user = $this->model->where('name',$post['name'])->find();
        if ($user) return $this->failed('该配置以存在');

        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('新增失败');
    }


    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,name,value,mark';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //查询是否重复的
        $find = $this->model->where('name', $post['name'])->where('id', '<>', $post['id'])->find();
        if ($find) return $this->failed('该配置以存在');
        $id = $post['id'];
        unset($post['id']);
        //执行修改数据
        $save = $this->model->where('id', $id)->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
}