<?php

namespace app\home\controller\notice;

use app\BaseController;
use app\common\model\UserModel as models;
use app\common\traites\PublicCrudTrait;
use app\common\model\Notice as NoticeModel;
use hg\apidoc\annotation as Apidoc;

/**
 * @Apidoc\Title("公告相关")
 * */
class Notice extends BaseController
{
    protected $model;
    use PublicCrudTrait;

    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Apidoc\Title("获取 通知")
     * @Apidoc\Method("POST")
     * @Apidoc\Returned("data", type="bool", desc="返回成功失败结果")
     */
    public function get_notice()
    {
        $res = (new NoticeModel())->page_list(['status' => 1, 'position' => 1], 20, 1);
        return show($res);
    }
}