<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;
use app\common\model\MoneyLog as models;

class MoneyLog extends Base
{
    protected $model;

    /**
     * 资金流动控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {

        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = [];
        isset($post['status']) && $map[] = ['a.status', '=', $post['status']];
//        isset($post['uid']) && $map[] = ['uid', '=', $post['uid']];
        isset($post['user_name']) && $map[] = ['c.user_name', 'like', '%' . $post['user_name'] . '%'];
        $order = 'a.id desc';
        isset($post['create_time_sort']) && $order = 'a.id ' . $post['create_time_sort'];

        // 0805 修改，不需要查询用户资金流动，底层逻辑改为查询代理资金流动
        $this->moneyLog($map, $limit, $page, $order);

        $list = $this->model->page_list($map, $limit, $page, $order);

//        $list =$this->model->alias('a')->where($map)->withJoin([
//            'user'	=>	['user_name']
//        ])->page($page, $limit)->paginate(['list_rows'=>$limit,'page'=>$page]);;

        return $this->success($list);
    }


    public function moneyLog($map, $limit, $page, $order)
    {
        $fields = 'a.id,a.order_sn,a.money,a.agent_uid,a.income_type,a.order_type,a.video,a.price,a.tip_number,a.channel_number,a.source,a.create_time,c.user_name as agent_user_name,b.title as video';
        $list = $this->model->agent_page_list($map, $fields, $limit, $page, $order);
        return $this->success($list);
    }

    /**
     * 列表（代理）
     * @return mixed
     */
    public function agent_list()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = array_filter($this->request->post());
        // 搜索字段：代理名称：订单号，收入类型，
        //只查询自己的
        $map[] = ['a.agent_uid', '=', session('admin_user.id')];
        //只查收入
        $map[] = ['a.type', '=', 1];

        isset($post['order_sn']) && $map[] = ['a.order_sn', '=', $post['order_sn']];
        isset($post['income_type']) && $map[] = ['a.income_type', '=', $post['income_type']];
//        isset($post['user_name'])&& $map[]= ['b.user_name', 'like', '%' . $post['user_name'] . '%'];
        $order = 'a.id desc';
//        isset($post['create_time_sort']) && $order = 'a.id ' . $post['create_time_sort'];
        $fields = 'a.id,a.order_sn,a.money,a.agent_uid,a.income_type,a.order_type,a.video,a.price,a.tip_number,a.channel_number,a.source,a.create_time,b.title as video';
        $list = $this->model->agent_page_list($map, $fields, $limit, $page, $order);

        return $this->success($list);
    }
}