<?php


namespace app\home\controller\login;

use app\home\controller\Base;
use app\common\model\UserModel as models;
use app\validate\home\Login as validates;
use think\exception\ValidateException;

class UpdatePwd extends Base
{
    protected $model;

    /**
     * 修改密码
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //修改密码  获取用户信息在修改密码
    public function change_pwd()
    {
        //过滤数据
        $postField = 'user_name,pwd,phone';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('edit_pwd')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return show([],config('ToConfig.http_code.error'),$e->getError());
        }
        $save = [
            'pwd'       => pwdEncryption($post['pwd']),
            'user_name' => $post['user_name'],
            'phone'     => $post['phone'] ?? '',
        ];
        //插入数据 查询手机号和旧密码是否匹配
        $find = $this->model->where(['id' => session('home_user.id')])->save($save);
        if (empty($find)) return show([],config('ToConfig.http_code.error'),'修改密码失败');
        return show();
    }

    //忘记密码
    public function forget()
    {
        //过滤数据
        $postField = 'phone,pwd';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('forget')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return show([],config('ToConfig.http_code.error'),$e->getError());
        }

        //判断输入账号是否正确
        if ($post['phone'] != session('home_user.phone')) return $this->failed('输入账号和登陆的不匹配');
        //插入数据
        $find = $this->model->where(['phone' => $post['phone']])
            ->save(['pwd' => pwdEncryption($post['pwd'])]);
        if (empty($find)) return show([],config('ToConfig.http_code.error'),'修改密码失败');
        return show();
    }
}